# Generated by Django 3.2.5 on 2022-01-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.ImageField(blank=True, default='default-project.jpg', null=True, upload_to='images/projects'),
        ),
    ]
