# Generated by Django 3.2.5 on 2022-01-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_alter_project_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='short_intro',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
